# Generated by Django 4.0.3 on 2022-04-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=60)),
                ('matricula', models.CharField(max_length=12, unique=True)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('disciplinas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=60)),
                ('matricula', models.CharField(max_length=12, unique=True)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso')),
                ('disciplinas', models.ManyToManyField(to='academico.disciplina')),
            ],
        ),
    ]
